### PR TITLE
Add Chat service & cover some edge cases

### PR DESCRIPTION
**Pull request by fraktality**
Covering cases where someone changes the name of Selection or ReplicatedStorage+minor formatting tweaks to maintain alignment when the tab size changes.

### CODE REVIEW

**Comment by evaera** [comment]
This change will break old mixins though :( need to add backwards compatibility with those

**Comment by fraktality** [comment]
<strike>where would it break them?</strike> ah, I see it now

**Comment by fraktality** [comment]
Will that patch work?

**Comment by evaera** [comment]
@Fraktality thank you, putting it in the next release. (:

**Pull request merged**
